version: 1.4.7.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017 RC
configuration: Release
platform:
- ARM
- x86
- x64
shallow_clone: true
clone_depth: 1
before_build:
- cmd: Nuget restore
build:
  project: Source/RawParser.sln
  parallel: true
  verbosity: detailed